# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 439ed0319b5b9f294acb0100b75736fd21b2d5c03aa079235f5e7cd278fc98381605559d2bca1c2fe7c442ac242196db40199fa637eab671873c1b2055d4c430

test:
  secret_key_base: 9dcc17b0369820f7d1e12cccc79fb22c9eaed980633845bc833e2a1fda9a8cb63658d179a82b83f0c3b1f9b80f54d340c4a64ee2be053cbd2a43cbda9f5f927f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
